# Generated by Django 3.0.2 on 2020-04-08 05:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to=core.models.recipe_image_field_path),
            preserve_default=False,
        ),
    ]
